import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import AOSProvider from "../components/providers/AOSProvider";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${oswald.variable}`}>
         <AOSProvider>{children}</AOSProvider>
      </body>
    </html>
  );
}
